# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov 02 20:45:14 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "温度监测系统", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.stack_view = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack_view.sizePolicy().hasHeightForWidth())
        self.stack_view.setSizePolicy(sizePolicy)
        self.stack_view.setObjectName(_fromUtf8("stack_view"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tbl_sensors = QtGui.QTableWidget(self.page)
        self.tbl_sensors.setObjectName(_fromUtf8("tbl_sensors"))
        self.tbl_sensors.setColumnCount(0)
        self.tbl_sensors.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_sensors)
        self.stack_view.addWidget(self.page)
        self.verticalLayout_2.addWidget(self.stack_view)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "视图", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "历史查询", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "系统设置", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "数据备份/恢复", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.doc_log = QtGui.QDockWidget(MainWindow)
        self.doc_log.setFloating(False)
        self.doc_log.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.doc_log.setWindowTitle(QtGui.QApplication.translate("MainWindow", "事件信息", None, QtGui.QApplication.UnicodeUTF8))
        self.doc_log.setObjectName(_fromUtf8("doc_log"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tbl_logs = QtGui.QTableWidget(self.dockWidgetContents)
        self.tbl_logs.setObjectName(_fromUtf8("tbl_logs"))
        self.tbl_logs.setColumnCount(2)
        self.tbl_logs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "时间", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_logs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "信息", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_logs.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tbl_logs)
        self.doc_log.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.doc_log)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_global_view = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/global_view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_global_view.setIcon(icon)
        self.act_global_view.setText(QtGui.QApplication.translate("MainWindow", "全局视图", None, QtGui.QApplication.UnicodeUTF8))
        self.act_global_view.setObjectName(_fromUtf8("act_global_view"))
        self.act_boiler_view = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/boiler_view.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_boiler_view.setIcon(icon1)
        self.act_boiler_view.setText(QtGui.QApplication.translate("MainWindow", "风炉视图", None, QtGui.QApplication.UnicodeUTF8))
        self.act_boiler_view.setObjectName(_fromUtf8("act_boiler_view"))
        self.act_query = QtGui.QAction(MainWindow)
        self.act_query.setEnabled(True)
        self.act_query.setText(QtGui.QApplication.translate("MainWindow", "温度历史查询", None, QtGui.QApplication.UnicodeUTF8))
        self.act_query.setVisible(True)
        self.act_query.setIconVisibleInMenu(True)
        self.act_query.setObjectName(_fromUtf8("act_query"))
        self.act_change_pwd = QtGui.QAction(MainWindow)
        self.act_change_pwd.setText(QtGui.QApplication.translate("MainWindow", "修改密码", None, QtGui.QApplication.UnicodeUTF8))
        self.act_change_pwd.setObjectName(_fromUtf8("act_change_pwd"))
        self.act_account_man = QtGui.QAction(MainWindow)
        self.act_account_man.setText(QtGui.QApplication.translate("MainWindow", "帐号管理", None, QtGui.QApplication.UnicodeUTF8))
        self.act_account_man.setVisible(False)
        self.act_account_man.setObjectName(_fromUtf8("act_account_man"))
        self.act_moni_conf = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_moni_conf.setIcon(icon2)
        self.act_moni_conf.setText(QtGui.QApplication.translate("MainWindow", "参数设置", None, QtGui.QApplication.UnicodeUTF8))
        self.act_moni_conf.setVisible(False)
        self.act_moni_conf.setObjectName(_fromUtf8("act_moni_conf"))
        self.act_backup = QtGui.QAction(MainWindow)
        self.act_backup.setText(QtGui.QApplication.translate("MainWindow", "数据备份", None, QtGui.QApplication.UnicodeUTF8))
        self.act_backup.setObjectName(_fromUtf8("act_backup"))
        self.act_recover = QtGui.QAction(MainWindow)
        self.act_recover.setText(QtGui.QApplication.translate("MainWindow", "数据恢复", None, QtGui.QApplication.UnicodeUTF8))
        self.act_recover.setObjectName(_fromUtf8("act_recover"))
        self.menu.addAction(self.act_global_view)
        self.menu.addAction(self.act_boiler_view)
        self.menu_2.addAction(self.act_query)
        self.menu_3.addAction(self.act_change_pwd)
        self.menu_3.addAction(self.act_account_man)
        self.menu_3.addAction(self.act_moni_conf)
        self.menu_4.addAction(self.act_backup)
        self.menu_4.addAction(self.act_recover)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.act_global_view)
        self.toolBar.addAction(self.act_boiler_view)
        self.toolBar.addAction(self.act_moni_conf)

        self.retranslateUi(MainWindow)
        self.stack_view.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        item = self.tbl_logs.horizontalHeaderItem(0)
        item = self.tbl_logs.horizontalHeaderItem(1)

import application_rc
