# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoringconfigdlg.ui'
#
# Created: Sun Sep 04 21:46:50 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MonitoringConfigDlg(object):
    def setupUi(self, MonitoringConfigDlg):
        MonitoringConfigDlg.setObjectName(_fromUtf8("MonitoringConfigDlg"))
        MonitoringConfigDlg.resize(594, 385)
        MonitoringConfigDlg.setWindowTitle(QtGui.QApplication.translate("MonitoringConfigDlg", "监控参数设置", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4 = QtGui.QVBoxLayout(MonitoringConfigDlg)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lst_configs = QtGui.QListWidget(MonitoringConfigDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_configs.sizePolicy().hasHeightForWidth())
        self.lst_configs.setSizePolicy(sizePolicy)
        self.lst_configs.setObjectName(_fromUtf8("lst_configs"))
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "监控范围设置", None, QtGui.QApplication.UnicodeUTF8))
        self.lst_configs.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "温度传感器设置", None, QtGui.QApplication.UnicodeUTF8))
        self.lst_configs.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "串口设置", None, QtGui.QApplication.UnicodeUTF8))
        self.lst_configs.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "其他设置", None, QtGui.QApplication.UnicodeUTF8))
        self.lst_configs.addItem(item)
        self.horizontalLayout_3.addWidget(self.lst_configs)
        self.stack_configs = QtGui.QStackedWidget(MonitoringConfigDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack_configs.sizePolicy().hasHeightForWidth())
        self.stack_configs.setSizePolicy(sizePolicy)
        self.stack_configs.setObjectName(_fromUtf8("stack_configs"))
        self.page_monitor_scope = QtGui.QWidget()
        self.page_monitor_scope.setObjectName(_fromUtf8("page_monitor_scope"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_monitor_scope)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.page_monitor_scope)
        self.groupBox.setTitle(QtGui.QApplication.translate("MonitoringConfigDlg", "监控范围设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "风炉数量：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spin_boiler_num = QtGui.QSpinBox(self.groupBox)
        self.spin_boiler_num.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_boiler_num.setMaximum(16)
        self.spin_boiler_num.setProperty("value", 7)
        self.spin_boiler_num.setObjectName(_fromUtf8("spin_boiler_num"))
        self.horizontalLayout.addWidget(self.spin_boiler_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "温度传感器数量：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spin_sensor_num = QtGui.QSpinBox(self.groupBox)
        self.spin_sensor_num.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_sensor_num.setMaximum(40)
        self.spin_sensor_num.setProperty("value", 20)
        self.spin_sensor_num.setObjectName(_fromUtf8("spin_sensor_num"))
        self.horizontalLayout_2.addWidget(self.spin_sensor_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "风机数量：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.spin_fan_num = QtGui.QSpinBox(self.groupBox)
        self.spin_fan_num.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_fan_num.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 个", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_fan_num.setMaximum(8)
        self.spin_fan_num.setProperty("value", 4)
        self.spin_fan_num.setObjectName(_fromUtf8("spin_fan_num"))
        self.horizontalLayout_7.addWidget(self.spin_fan_num)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.btn_apply_scope = QtGui.QPushButton(self.page_monitor_scope)
        self.btn_apply_scope.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "应用", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_apply_scope.setObjectName(_fromUtf8("btn_apply_scope"))
        self.verticalLayout_2.addWidget(self.btn_apply_scope)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.stack_configs.addWidget(self.page_monitor_scope)
        self.sensor_config = QtGui.QWidget()
        self.sensor_config.setObjectName(_fromUtf8("sensor_config"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sensor_config)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.sensor_config)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MonitoringConfigDlg", "温度传感器设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "风炉：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbo_boiler = QtGui.QComboBox(self.groupBox_2)
        self.cbo_boiler.setObjectName(_fromUtf8("cbo_boiler"))
        self.gridLayout.addWidget(self.cbo_boiler, 0, 1, 1, 2)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "最低记录温度：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.spin_low_temp = QtGui.QSpinBox(self.groupBox_2)
        self.spin_low_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_low_temp.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " ℃", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_low_temp.setMaximum(99)
        self.spin_low_temp.setProperty("value", 50)
        self.spin_low_temp.setObjectName(_fromUtf8("spin_low_temp"))
        self.gridLayout.addWidget(self.spin_low_temp, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "最高记录温度：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.spin_hi_temp = QtGui.QSpinBox(self.groupBox_2)
        self.spin_hi_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_hi_temp.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " ℃", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_hi_temp.setProperty("value", 75)
        self.spin_hi_temp.setObjectName(_fromUtf8("spin_hi_temp"))
        self.gridLayout.addWidget(self.spin_hi_temp, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "报警温度：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.spin_alert_temp = QtGui.QSpinBox(self.groupBox_2)
        self.spin_alert_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_alert_temp.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " ℃", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_alert_temp.setProperty("value", 71)
        self.spin_alert_temp.setObjectName(_fromUtf8("spin_alert_temp"))
        self.gridLayout.addWidget(self.spin_alert_temp, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "报警时长：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.spin_alert_time = QtGui.QSpinBox(self.groupBox_2)
        self.spin_alert_time.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_alert_time.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 秒", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_alert_time.setProperty("value", 15)
        self.spin_alert_time.setObjectName(_fromUtf8("spin_alert_time"))
        self.gridLayout.addWidget(self.spin_alert_time, 5, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "巴氏消毒时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 2)
        self.spin_pasteu_time = QtGui.QSpinBox(self.groupBox_2)
        self.spin_pasteu_time.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_pasteu_time.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 分钟", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_pasteu_time.setProperty("value", 35)
        self.spin_pasteu_time.setObjectName(_fromUtf8("spin_pasteu_time"))
        self.gridLayout.addWidget(self.spin_pasteu_time, 6, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "消毒完成报警时长：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 2)
        self.spin_pasteu_alert_time = QtGui.QSpinBox(self.groupBox_2)
        self.spin_pasteu_alert_time.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_pasteu_alert_time.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 秒", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_pasteu_alert_time.setProperty("value", 20)
        self.spin_pasteu_alert_time.setObjectName(_fromUtf8("spin_pasteu_alert_time"))
        self.gridLayout.addWidget(self.spin_pasteu_alert_time, 7, 2, 1, 1)
        self.chk_hi_temp_alert = QtGui.QCheckBox(self.groupBox_2)
        self.chk_hi_temp_alert.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "温度过高自动报警", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_hi_temp_alert.setChecked(True)
        self.chk_hi_temp_alert.setTristate(False)
        self.chk_hi_temp_alert.setObjectName(_fromUtf8("chk_hi_temp_alert"))
        self.gridLayout.addWidget(self.chk_hi_temp_alert, 8, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.btn_apply_sensor = QtGui.QPushButton(self.sensor_config)
        self.btn_apply_sensor.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "应用", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_apply_sensor.setObjectName(_fromUtf8("btn_apply_sensor"))
        self.verticalLayout_3.addWidget(self.btn_apply_sensor)
        spacerItem1 = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stack_configs.addWidget(self.sensor_config)
        self.page_com = QtGui.QWidget()
        self.page_com.setObjectName(_fromUtf8("page_com"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_com)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.page_com)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MonitoringConfigDlg", "串口设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "选择串口：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.cbo_com = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_com.sizePolicy().hasHeightForWidth())
        self.cbo_com.setSizePolicy(sizePolicy)
        self.cbo_com.setObjectName(_fromUtf8("cbo_com"))
        self.horizontalLayout_4.addWidget(self.cbo_com)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "波特率：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.cbo_baudrate = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_baudrate.sizePolicy().hasHeightForWidth())
        self.cbo_baudrate.setSizePolicy(sizePolicy)
        self.cbo_baudrate.setObjectName(_fromUtf8("cbo_baudrate"))
        self.cbo_baudrate.addItem(_fromUtf8(""))
        self.cbo_baudrate.setItemText(0, QtGui.QApplication.translate("MonitoringConfigDlg", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_baudrate.addItem(_fromUtf8(""))
        self.cbo_baudrate.setItemText(1, QtGui.QApplication.translate("MonitoringConfigDlg", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_baudrate.addItem(_fromUtf8(""))
        self.cbo_baudrate.setItemText(2, QtGui.QApplication.translate("MonitoringConfigDlg", "14400", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_baudrate.addItem(_fromUtf8(""))
        self.cbo_baudrate.setItemText(3, QtGui.QApplication.translate("MonitoringConfigDlg", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_5.addWidget(self.cbo_baudrate)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "采集间隔时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.spin_acq_interval = QtGui.QSpinBox(self.groupBox_4)
        self.spin_acq_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_acq_interval.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 秒", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_acq_interval.setProperty("value", 1)
        self.spin_acq_interval.setObjectName(_fromUtf8("spin_acq_interval"))
        self.horizontalLayout_6.addWidget(self.spin_acq_interval)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "串口超时：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.spin_timeout = QtGui.QSpinBox(self.groupBox_4)
        self.spin_timeout.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_timeout.setSuffix(QtGui.QApplication.translate("MonitoringConfigDlg", " 毫秒", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_timeout.setMaximum(100000)
        self.spin_timeout.setSingleStep(100)
        self.spin_timeout.setProperty("value", 1000)
        self.spin_timeout.setObjectName(_fromUtf8("spin_timeout"))
        self.horizontalLayout_8.addWidget(self.spin_timeout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.btn_apply_com = QtGui.QPushButton(self.page_com)
        self.btn_apply_com.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "应用", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_apply_com.setObjectName(_fromUtf8("btn_apply_com"))
        self.verticalLayout_7.addWidget(self.btn_apply_com)
        spacerItem2 = QtGui.QSpacerItem(20, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.stack_configs.addWidget(self.page_com)
        self.page_others = QtGui.QWidget()
        self.page_others.setObjectName(_fromUtf8("page_others"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_others)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_others)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MonitoringConfigDlg", "其他信息", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "公司信息：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.edit_company_info = QtGui.QLineEdit(self.groupBox_3)
        self.edit_company_info.setObjectName(_fromUtf8("edit_company_info"))
        self.gridLayout_2.addWidget(self.edit_company_info, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.btn_apply_others = QtGui.QPushButton(self.page_others)
        self.btn_apply_others.setText(QtGui.QApplication.translate("MonitoringConfigDlg", "应用", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_apply_others.setObjectName(_fromUtf8("btn_apply_others"))
        self.verticalLayout_5.addWidget(self.btn_apply_others)
        spacerItem3 = QtGui.QSpacerItem(20, 228, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.stack_configs.addWidget(self.page_others)
        self.horizontalLayout_3.addWidget(self.stack_configs)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(MonitoringConfigDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(MonitoringConfigDlg)
        self.lst_configs.setCurrentRow(-1)
        self.stack_configs.setCurrentIndex(0)
        self.cbo_boiler.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MonitoringConfigDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MonitoringConfigDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(MonitoringConfigDlg)

    def retranslateUi(self, MonitoringConfigDlg):
        __sortingEnabled = self.lst_configs.isSortingEnabled()
        self.lst_configs.setSortingEnabled(False)
        item = self.lst_configs.item(0)
        item = self.lst_configs.item(1)
        item = self.lst_configs.item(2)
        item = self.lst_configs.item(3)
        self.lst_configs.setSortingEnabled(__sortingEnabled)

